#!/usr/bin/python3
from models.basemodel import BaseModel, Base
from sqlalchemy import Column, Integer
from sqlalchemy.orm import relationship

class User(BaseModel, Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, autoincrement=True)
    posts = relationship("Post", back_populates="user")
